"""rename colum id

Revision ID: ba3058d0de1d
Revises: b063ff469f5a
Create Date: 2025-03-30 16:12:00.721197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3058d0de1d'
down_revision: Union[str, None] = 'b063ff469f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_info', sa.Column('resource_id', sa.UUID(), nullable=False))
    op.drop_column('wallet_info', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_info', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('wallet_info', 'resource_id')
    # ### end Alembic commands ###
