"""qweqwe

Revision ID: 0ac3576538f7
Revises: ba3058d0de1d
Create Date: 2025-04-06 19:39:14.299660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac3576538f7'
down_revision: Union[str, None] = 'ba3058d0de1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_info', 'balance',
               existing_type=sa.NUMERIC(precision=50, scale=10),
               type_=sa.DECIMAL(precision=50, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_info', 'balance',
               existing_type=sa.DECIMAL(precision=50, scale=2),
               type_=sa.NUMERIC(precision=50, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###
